import React, { useEffect, useMemo, useState } from "react";
import { BookOpen, Brain, CheckCircle2, ChevronRight, Clock3, HelpCircle, Library, LogIn, LogOut, Search, Sparkles, Target, TrendingUp } from "lucide-react";
import { GoogleAuthProvider, getRedirectResult, onAuthStateChanged, signInWithPopup, signInWithRedirect, signOut } from "firebase/auth";
import { doc, onSnapshot } from "firebase/firestore";
import { auth, authPersistenceReady, db, firebaseConfigured } from "./lib/firebase";
import { flattenDeckCards, subscribeToUserDecks } from "./services/decks";
import StudySession from "./components/StudySession";
import HelpPage from "./components/HelpPage";
import "./styles.css";
import "./study-ui.css";

function authErrorMessage(error) { const code = error?.code || ""; if (code.includes("unauthorized-domain")) return "Este domínio ainda não está autorizado no Firebase Authentication."; if (code.includes("operation-not-allowed")) return "O login com Google não está ativado no Firebase Authentication."; if (code.includes("popup-closed-by-user")) return "A janela de login foi fechada antes de concluir."; if (code.includes("network-request-failed")) return "Falha de conexão. Verifique sua internet."; return error?.message || "Não foi possível entrar com o Google."; }
function LoginScreen({ onLogin, busy, error }) { return <main className="login-screen"><div className="login-card"><div className="brand login-brand"><div className="brand-mark"><Brain size={25} /></div><div><strong>MemoriaFlash</strong><span>Estude melhor</span></div></div><div className="login-icon"><BookOpen size={34} /></div><h1>Seu espaço para estudar.</h1><p>Acesse seus baralhos, revise seus cards e acompanhe seu progresso em qualquer computador.</p><button className="primary login-button" onClick={onLogin} disabled={busy || !firebaseConfigured}><LogIn size={18} />{busy ? "Entrando..." : "Entrar com Google"}</button>{!firebaseConfigured && <small>Firebase não está configurado neste ambiente.</small>}{error && <div className="auth-error">{error}</div>}<div className="login-benefits"><span>✓ Baralhos sincronizados</span><span>✓ Progresso sincronizado</span><span>✓ Estudo no computador</span></div></div></main>; }
function getDueCards(decks) { const now = Date.now(); return flattenDeckCards(decks).filter((card) => { const due = new Date(card.dueDate || 0).getTime(); return Number.isFinite(due) && due <= now; }); }
function getDeckProgress(deck) { const cards = Array.isArray(deck?.cards) ? deck.cards : []; if (!cards.length) return 0; const due = cards.filter((card) => { const date = new Date(card.dueDate || 0).getTime(); return Number.isFinite(date) && date <= Date.now(); }).length; return Math.max(0, Math.min(100, Math.round(((cards.length - due) / cards.length) * 100))); }
function Home({ user, decks, dueCards, onStudy, onLibrary }) { const firstName = user.displayName?.split(" ")[0] || "estudante"; const cards = flattenDeckCards(decks); return <div className="page study-page"><section className="study-hero"><div><span className="eyebrow"><Sparkles size={14} /> SEU ESPAÇO DE ESTUDO</span><h1>Olá, {firstName}.</h1><p>Escolha um baralho e continue exatamente de onde parou.</p></div><button className="primary hero-action" onClick={onLibrary}><Library size={17} /> Ver biblioteca</button></section><section className="study-stats"><div className="study-stat"><Library size={20} /><div><strong>{decks.length}</strong><span>baralhos</span></div></div><div className="study-stat"><BookOpen size={20} /><div><strong>{cards.length.toLocaleString("pt-BR")}</strong><span>cards</span></div></div><div className="study-stat"><Clock3 size={20} /><div><strong>{dueCards.length.toLocaleString("pt-BR")}</strong><span>para revisar</span></div></div></section>{dueCards.length > 0 && <section className="review-card"><div className="review-icon"><Target size={22} /></div><div className="review-copy"><strong>Você tem {dueCards.length} {dueCards.length === 1 ? "card" : "cards"} para revisar</strong><span>Uma revisão curta agora ajuda a manter o conteúdo na memória.</span></div><button className="primary" onClick={() => onStudy(null, dueCards)}>Começar revisão <ChevronRight size={17} /></button></section>}<section className="content-section"><div className="section-head"><div><span className="eyebrow">CONTINUAR ESTUDANDO</span><h2>Seus baralhos</h2></div>{decks.length > 4 && <button className="text-button" onClick={onLibrary}>Ver todos <ChevronRight size={15} /></button>}</div>{decks.length ? <div className="deck-grid">{decks.slice(0, 6).map((deck) => <DeckCard key={deck.id} deck={deck} onStudy={onStudy} />)}</div> : <EmptyState title="Sua biblioteca está vazia" text="Os baralhos disponíveis para sua conta aparecerão aqui." action="Abrir biblioteca" onClick={onLibrary} />}</section></div>; }
function DeckCard({ deck, onStudy }) { const progress = getDeckProgress(deck); return <article className="deck-card"><div className="deck-card-icon"><BookOpen size={20} /></div><div className="deck-card-body"><h3 title={deck.title}>{deck.title}</h3><p>{deck.cards.length} cards · {deck.category || "Geral"}</p><div className="progress-bar"><span style={{ width: `${progress}%` }} /></div><div className="deck-card-foot"><span>{progress}% em dia</span><button className="study-link" onClick={() => onStudy(deck)}>Estudar <ChevronRight size={15} /></button></div></div></article>; }
function LibraryPage({ decks, onStudy }) { const [query, setQuery] = useState(""); const filtered = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return decks; return decks.filter((deck) => `${deck.title} ${deck.category} ${deck.description}`.toLowerCase().includes(q)); }, [decks, query]); return <div className="page"><div className="page-title"><span className="eyebrow"><Library size={15} /> BIBLIOTECA</span><h1>O que você quer estudar?</h1><p>Encontre seus baralhos e comece a estudar.</p></div><div className="search-box"><Search size={18} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar por matéria, assunto ou baralho..." aria-label="Buscar baralhos" /></div>{filtered.length ? <div className="library-grid">{filtered.map((deck) => <button className="library-card" key={deck.id} onClick={() => onStudy(deck)}><div className="library-card-icon"><BookOpen size={21} /></div><div><h3>{deck.title}</h3><span>{deck.cards.length} cards · {deck.category || "Geral"}</span></div><ChevronRight size={18} /></button>)}</div> : <EmptyState title={query ? "Nenhum baralho encontrado" : "Sua biblioteca está vazia"} text={query ? "Tente buscar por outro nome ou assunto." : "Quando seus baralhos estiverem sincronizados, eles aparecerão aqui."} />}</div>; }
function ProgressPage({ decks, dueCards, isPro }) { const cards = flattenDeckCards(decks); const percent = cards.length ? Math.max(0, Math.round((1 - dueCards.length / cards.length) * 100)) : 0; return <div className="page"><div className="page-title"><span className="eyebrow"><TrendingUp size={15} /> PROGRESSO</span><h1>Seu desempenho</h1><p>Acompanhe sua rotina de revisão.</p></div><section className="progress-summary"><div><span className="eyebrow">CARDS EM DIA</span><strong>{percent}%</strong><p>{dueCards.length ? `${dueCards.length} cards aguardam revisão.` : "Nenhum card vencido agora."}</p></div><div className="progress-ring"><strong>{percent}%</strong></div></section><section className="study-stats"><div className="study-stat"><Library size={20} /><div><strong>{decks.length}</strong><span>baralhos</span></div></div><div className="study-stat"><BookOpen size={20} /><div><strong>{cards.length}</strong><span>cards</span></div></div><div className="study-stat"><CheckCircle2 size={20} /><div><strong>{dueCards.length}</strong><span>para revisar</span></div></div></section><section className="content-section"><div className="section-head"><div><span className="eyebrow">VISÃO POR BARALHO</span><h2>Revisão</h2></div></div><div className="progress-list">{decks.length ? decks.slice(0, 12).map((deck) => <ProgressRow key={deck.id} deck={deck} />) : <EmptyState title="Sem dados de estudo" text="Seus baralhos aparecerão aqui quando estiverem disponíveis." />}</div></section>{!isPro && <div className="plan-note"><strong>Plano gratuito</strong><span>Continue estudando normalmente.</span></div>}</div>; }
function ProgressRow({ deck }) { const progress = getDeckProgress(deck); return <div className="progress-row"><div className="progress-row-head"><span>{deck.title}</span><strong>{progress}%</strong></div><div className="progress-bar"><span style={{ width: `${progress}%` }} /></div><small>{deck.cards.length} cards</small></div>; }
function EmptyState({ title, text, action, onClick }) { return <div className="empty-state"><div className="empty-icon"><BookOpen size={22} /></div><h3>{title}</h3><p>{text}</p>{action && <button className="secondary" onClick={onClick}>{action}</button>}</div>; }
function MobileNav({ tab, setTab }) { const items = [{ key: "home", label: "Início", Icon: Sparkles }, { key: "library", label: "Biblioteca", Icon: Library }, { key: "stats", label: "Progresso", Icon: TrendingUp }, { key: "help", label: "Ajuda", Icon: HelpCircle }]; return <nav className="mobile-nav">{items.map(({ key, label, Icon }) => <button key={key} className={tab === key ? "active" : ""} onClick={() => setTab(key)}><Icon size={18} /><span>{label}</span></button>)}</nav>; }
function App() { const [user, setUser] = useState(null); const [authReady, setAuthReady] = useState(!auth); const [authBusy, setAuthBusy] = useState(false); const [authError, setAuthError] = useState(""); const [tab, setTab] = useState("home"); const [decks, setDecks] = useState([]); const [deckError, setDeckError] = useState(""); const [subscription, setSubscription] = useState({ isPro: false }); const [selectedDeck, setSelectedDeck] = useState(null); const [studyCards, setStudyCards] = useState([]); const [reportCard, setReportCard] = useState(null);
  useEffect(() => { if (!auth) { setAuthReady(true); return undefined; } let active = true; const unsubscribe = onAuthStateChanged(auth, (nextUser) => { if (!active) return; setUser(nextUser); setAuthReady(true); setAuthBusy(false); }); getRedirectResult(auth).catch((error) => { if (!active || error?.code === "auth/no-auth-event") return; setAuthError(authErrorMessage(error)); setAuthBusy(false); }); return () => { active = false; unsubscribe(); }; }, []);
  useEffect(() => { if (!user) { setDecks([]); setDeckError(""); return undefined; } return subscribeToUserDecks(user.uid, setDecks, () => setDeckError("Não foi possível sincronizar seus baralhos.")); }, [user]);
  useEffect(() => { if (!db || !user) { setSubscription({ isPro: false }); return undefined; } return onSnapshot(doc(db, "userStats", user.uid), (snap) => { const data = snap.exists() ? snap.data() : {}; const expiry = data.proExpiryDate || data.proExpiryDateIso; const expiryMs = expiry ? new Date(expiry).getTime() : NaN; setSubscription({ isPro: Boolean(data.isPro) && !(Number.isFinite(expiryMs) && expiryMs <= Date.now()) }); }, () => setSubscription({ isPro: false })); }, [user]);
  const dueCards = useMemo(() => getDueCards(decks), [decks]);
  async function login() { if (!auth || !firebaseConfigured || authBusy) return; setAuthBusy(true); setAuthError(""); try { await authPersistenceReady; const provider = new GoogleAuthProvider(); provider.setCustomParameters({ prompt: "select_account" }); await signInWithPopup(auth, provider); } catch (error) { try { const code = error?.code || ""; if (code.includes("popup-blocked") || code.includes("popup-failed") || code.includes("operation-not-supported-in-this-environment")) { const provider = new GoogleAuthProvider(); provider.setCustomParameters({ prompt: "select_account" }); await signInWithRedirect(auth, provider); return; } setAuthError(authErrorMessage(error)); } catch (fallbackError) { setAuthError(authErrorMessage(fallbackError)); } finally { setAuthBusy(false); } } }
  async function logout() { if (!auth || authBusy) return; setAuthBusy(true); try { await signOut(auth); setTab("home"); setSelectedDeck(null); setStudyCards([]); setReportCard(null); } catch (error) { setAuthError(authErrorMessage(error)); } finally { setAuthBusy(false); } }
  function startStudy(deck, cards = deck?.cards || []) { setSelectedDeck(deck || null); setStudyCards(Array.isArray(cards) ? cards : []); setTab("study"); }
  function reportCurrentCard(card) { setReportCard(card ? { ...card, deckId: card.deckId || selectedDeck?.id || null, deckTitle: card.deckTitle || selectedDeck?.title || null } : null); setTab("help"); }
  function goHelp() { setReportCard(null); setTab("help"); }
  if (!authReady) return <div className="loading-state"><span className="spinner" /> Verificando sua conta...</div>; if (!user) return <LoginScreen onLogin={login} busy={authBusy} error={authError} />; if (tab === "study") return <StudySession user={user} deck={selectedDeck} cards={studyCards} onHelp={reportCurrentCard} onExit={() => { setTab("library"); setSelectedDeck(null); setStudyCards([]); }} />;
  const navItem = (key, label, Icon) => <button className={tab === key ? "nav-item active" : "nav-item"} onClick={() => setTab(key)}><Icon size={19} />{label}</button>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Brain size={22} /></div><div><strong>MemoriaFlash</strong><span>{user.displayName || "Sua conta"}</span></div></div><nav>{navItem("home", "Início", Sparkles)}{navItem("library", "Biblioteca", Library)}{navItem("stats", "Progresso", TrendingUp)}{navItem("help", "Ajuda", HelpCircle)}</nav><div className="sidebar-bottom"><div className="study-account"><div className="study-account-avatar">{user.displayName?.[0]?.toUpperCase() || "M"}</div><div><strong>{subscription.isPro ? "Plano PRO" : "Plano gratuito"}</strong><span>{user.email}</span></div></div><button className="nav-item" onClick={logout} disabled={authBusy}><LogOut size={19} />{authBusy ? "Saindo..." : "Sair"}</button>{deckError && <small className="feedback-status">{deckError}</small>}</div></aside><main className="main"><header className="topbar"><div className="mobile-brand"><Brain size={20} />MemoriaFlash</div><div className="topbar-spacer" /><button className="topbar-help" onClick={goHelp} aria-label="Abrir ajuda"><HelpCircle size={20} /><span>Ajuda</span></button><div className="topbar-user">{user.displayName?.[0]?.toUpperCase() || "M"}</div></header>{tab === "home" && <Home user={user} decks={decks} dueCards={dueCards} onStudy={startStudy} onLibrary={() => setTab("library")} />}{tab === "library" && <LibraryPage decks={decks} onStudy={startStudy} />}{tab === "stats" && <ProgressPage decks={decks} dueCards={dueCards} isPro={subscription.isPro} />}{tab === "help" && <HelpPage user={user} reportCard={reportCard} onClearCard={() => setReportCard(null)} />}</main><MobileNav tab={tab} setTab={(next) => { if (next === "help") goHelp(); else setTab(next); }} /></div>; }
createRoot(document.getElementById("root")).render(<App />);
